### ISSUE TITLE
Access violation exception on windows 8.1 / server 2012

### ISSUE THREAD

**Issue by levenleven** [aybe/Windows-API-Code-Pack-1.1#2]
Hi,
The exception is thrown when trying to read array property values (Shell) like System.Authors and other.

The problem was fixed for me by changing
//[FieldOffset(12)] original
        [FieldOffset(16)]
        IntPtr _ptr2;
in PropVariant.cs

But I'm not really into pInvoke/c++ stuff, so please take a look at this.

Thanks,
Leven

**Comment by aybe** [comment]
I will not fix it as it could/would break other things which would need lots of testing and since there is no test suite to count on.

You have the following alternative:

https://social.msdn.microsoft.com/forums/vstudio/en-us/08d4f986-b416-4a94-ae0c-13361c9929d1/extract-file-properties

It relies on Shell32 and works for any architecture, you will have to come up with some mechanism to make your life easier in using it but it provides all the details you will ever need to know from a file.

**Comment by levenleven** [comment]
Shell32 is really limited and it can't fetch all the properties that code pack can (GPS coordinates for example). But you are right, without tests it is pretty dangerous..

**Comment by aybe** [comment]
Yes, the thing is that this API code pack is a pretty strange beast in itself, it is mainly provided here as a 'legacy' tech. that never went official from MS.

Personally I'm not using it anymore, whenever there's serious stuff involved I would go C++/CLI instead, but I reckon that not everyone can afford it.

Just a guess but maybe you can use some command-line tool that would do all the dirty work and you'll just have to parse a text file instead, for instance http://www.sno.phy.queensu.ca/~phil/exiftool/. (invoking Process.Start with a hidden window)

**Comment by levenleven** [comment]
Thanks, will check it out
